import ProjectDescription
// import ProjectDescriptionHelpers

let appName = "BananaApp"

func makeBundleIdForName(_ name: String) -> String { "examples.mokagio.\(name)" }

let infoPlist: [String: InfoPlist.Value] = [
    "CFBundleShortVersionString": "1.0",
    "CFBundleVersion": "1",
    // I've found these values by diffing an app with SwiftUI lifecycle
    // generated by Xcode. I haven't tried disabling some to see if the app
    // still runs.
    "CFBundlePackageType": "$(PRODUCT_BUNDLE_PACKAGE_TYPE)",
    "UIApplicationSceneManifest": [
        "UIApplicationSupportsMultipleScenes": true,
    ],
    "UILaunchScreen": [:],
    "UIApplicationSupportsIndirectInputEvents": true
]

let project = Project(
    name: appName,
    organizationName: "mokagio",
    targets: [
        Target(
            name: "BananaApp",
            platform: .iOS,
            product: .app,
            bundleId: makeBundleIdForName(appName),
            infoPlist: .extendingDefault(with: infoPlist),
            sources: ["./Sources/**"]
        ),
        Target(
            name: "\(appName)Tests",
            platform: .iOS,
            product: .unitTests,
            bundleId: makeBundleIdForName("\(appName)Tests"),
            infoPlist: .default,
            sources: ["./Tests/**"],
            dependencies: [
                .target(name: "\(appName)")
            ]
        )
    ]
)
